### ISSUE TITLE
McME 1.1

### ISSUE THREAD

**Issue by mchorse** [mchorse/mcme#2]
This is issue is development continue for McME. This release is planned for later versions of Blockbuster mod. Here are the features:
## General
- [ ] Animation cosmetics
## Texture Editor
- [ ] Brushes (pencil and eraser)
- [ ] Gradient tool
- [ ] Line tool
- [ ] Color history in color picker
- [ ] Use second color when holding shift down
## Model Editor
- [ ] Grass floor under the model
- [ ] An interesting wallpaper
- [ ] Select multiple limbs
- [ ] Anchor indicator

Some of features are suggested by @NlL5.

**Comment by NlL5** [comment]
Suggestion for Texture Editor:
Use second color when holding shift down

Btw, great work so far :-)

**Comment by mchorse** [comment]
Nice suggestion, thanks!

> Btw, great work so far :-)

Thanks! :)
I think that was the hardest part, because I'm halfway finished with models (see this [tweet](https://twitter.com/McHorsy/status/772793975396761600)).

**Comment by NlL5** [comment]
Cool, nice! :D

**Comment by NlL5** [comment]
Suggestion for Model Editor:
A little cross or coordinate axis to indicate where the anchor of the current selected limb is positioned.

(Btw, if these suggestions don't fit with what you're planning or are too heavy to implement, you can just delete them.)

**Comment by mchorse** [comment]
> Suggestion for Model Editor:
> A little cross or coordinate axis to indicate where the anchor of the current selected limb is positioned.

This is a good idea, I like it!

> (Btw, if these suggestions don't fit with what you're planning or are too heavy to implement, you can just delete them.)

Or I'll just move them to the next release :D
