### ISSUE TITLE
Possible bugs and errors

### ISSUE THREAD

**Issue by NlL5** [mchorse/mcme#3]
# Texture Editor
### JS errors
- [x] Choose Picker; click outside the canvas<br>_Uncaught TypeError: Cannot read property '0' of null_<br>
  `setColor   @   picker.js:103`<br>
  `onMouseDown    @   picker.js:24`<br>
  `onMouseDown    @   toolbar.js:78`<br>
  `onMouseDown    @   editor.js:224`<br>
  `onMouseDown    @   app.js:143`
### Bugs - more or less
- [x] Putting negative values in the Canvas Option Size results in a 32x16 canvas that is centered at the negative coordinates and is not drawable.<br>Importing a skin or generating a texture mapping is not possible in this state and exporting gives a big "transparent" texture.<br>(I expected a 0*0 canvas or an error indication.)
- [x] Putting decimal values like 10.9 in the Canvas Option Size results in an invalid canvas size.<br>(I expected floor rounding or an error indication.)
### Behavior thinks
- [x] Pasting rgba or hsla CSS colors into the Color Picker results in overlaying the current color with the new color. Is this behavior correct?
- [x] Importing a skin doesn't change the canvas size. But I guess this is correct!
# Model Editor
### JS errors
- [x] In the Model Settings, enabling and disabling the HD shadows, before shadow rendering is finished results in<br>_Uncaught TypeError: Cannot read property 'dispose' of null_<br>
  `hdChange   @   settings.js:165`<br>
  `notifyChanges  @   settings.js:105`<br>
  `(anonymous function)   @   settings.js:34`<br>
  The exact same error occurs when Lightning is disabled and HD shadows gets toggled. (Or sometimes other combinations.)
- [x] Putting '0' into one of the Size fields of a limb:<br>_Uncaught TypeError: Cannot read property '0' of undefined_<br>`side    @   uv.js:58`<br>
  `cube   @   uv.js:71`<br>
  `mapUV  @   model.js:261`<br>
  `regenerateLimb @   model.js:240`<br>
  `regenerate @   properties.js:147`<br>
  `sizeChange @   properties.js:126`<br>
  `change @   properties.js:56`<br>
  `(anonymous function)   @   properties.js:30
- [x] Putting '0' into one of the Scale fields of Poses results in a lot warnings of three.js<br>_THREE.Matrix3.getInverse(): can't invert matrix, determinant is 0_
- [x] Importing a json file with invalid syntax results in SyntaxError.... yeah :smile:
### Bugs
- [x] Pressing 'S' in the Model Editor toggles the settings, but does not select the Scale tool.
- [x] Changing the pose doesn't work since one of the last commits I think:<br>_Uncaught TypeError: pose.applyPose is not a function_<br>
  `poseChange @   poses.js:100`
## Miscellaneous
- [x] In Chrome or Chromium, some elements get selected when holding down the mouse button and move it outside the texture / model editor. ([See attachment](https://cloud.githubusercontent.com/assets/20781376/18255997/c47798c0-73af-11e6-896e-b9a94c541f5e.png))<br>To prevent this, you could use css like described  [here](http://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting-using-css?answertab=votes#tab-top).

**Comment by mchorse** [comment]
Astounding work, many thanks! 😄 

I'll work on those bugs and design flaws tomorrow, except the ones that breaking the app (like poses).

> Pasting rgba or hsla CSS colors into the Color Picker results in overlaying the current color with the new color. Is this behavior correct?

Not, that's not correct behavior. I'll change that you could see checked pattern if the color is semi- or transparent.

> Importing a skin doesn't change the canvas size. But I guess this is correct!

Yes, this is correct.

> Pressing 'S' in the Model Editor toggles the settings, but does not select the Scale tool.

It's actually `C`, did I put wrong title for scale tool?

**Comment by NlL5** [comment]
You're welcome ^_^

> I'll change that you could see checked pattern if the color is semi- or transparent.

Oh cool!

> It's actually C, did I put wrong title for scale tool?

Ah ok, then it's only a typo in the tool title. ;-)

**Comment by mchorse** [comment]
I turned your issue into ToDo list, now I'm going start fixing those bugs.

![Bug control](http://s2.quickmeme.com/img/f6/f664a12f789f413b5193c1ae3897ad6a10498de4fe4093c49f8d06f37ca855b0.jpg)

**Comment by mchorse** [comment]
I fixed everything in the list, but I have some doubt about fixing this:

> In the Model Settings, enabling and disabling the HD shadows, before shadow rendering is finished 

Could you confirm this fix? When I try reproducing it, my browser freezes for few seconds thus not allowing me to press that checkbox again.

**Comment by NlL5** [comment]
Yes, it's fixed! Nice!!

(Will check the rest tomorrow.)

**Comment by NlL5** [comment]
Oh lol.. I didn't know what 'Close and comment' was all about :smile:

**Comment by NlL5** [comment]
When I put a negative number (not 0) into one of the Size fields of the Texture Editor, it says that "You can't use zero as one of canvas' size components (0x32)", but I think that's alright! :blush: 

Addition to:

> Putting '0' into one of the Scale fields of Poses results in a lot warnings of three.js<br>_THREE.Matrix3.getInverse(): can't invert matrix, determinant is 0_

This issue got fixed, but still can be produced by using the scale tool and resize a limb to a size of 0x0x0

**Comment by mchorse** [comment]
Everything is patched 😜

**Comment by mchorse** [comment]
Thanks for helping! :)
